### ISSUE TITLE
ReactomeGSA:Error in curl::curl_fetch_memory(url, handle = handle) :   HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by rpauly** [reactome/ReactomeGSA#14]
I tried to run Reactome GSA on a single cell Seurat object using the instructions (https://bioconductor.org/packages/release/bioc/vignettes/ReactomeGSA/inst/doc/analysing-scRNAseq.html). I get an error though:
> gsva_result <- analyse_sc_clusters(rds_file, verbose = TRUE)
Calculating average cluster expression...
Converting expression data to string... (This may take a moment)
Conversion complete
Submitting request to Reactome API...
Compressing request data...
Error in curl::curl_fetch_memory(url, handle = handle) :
  HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
 
Any suggestions?
Thanks,
Rini

**Comment by jgriss** [comment]
Hi @rpauly,

Thanks a lot for your interest in using ReactomeGSA! Sorry to hear that you're having problems!

We updated the system today. Therefore, for about 1-2 minutes analysis requests may have had issues.

Nevertheless, if you could provide me with a timestamp when you run your analysis I can check the logs to see where the issue lies (you can also simply retry and let me know at what time the new attempt failed).

Kind regards,
Johannes

**Comment by rpauly** [comment]
Thanks for your reply!
I just set it up again...and it is still working on the "Compressing
request data" for an hour now. How long does it usually take for this step?

Thanks again for your help,
Rini

**Comment by jgriss** [comment]
Hi Rini,

The "compressing data" step is a simple gzip commpression of the average 
expression values per cluster. This is done directly by R and not our 
package.

If this takes that long it means that A) your R session crashed or ran 
out of memory or B) your dataset is quite big.

I guess you performed some kind of Q/C on your features. How many genes 
and clusters to you have? How much memory does your machine have and how 
much of it is available before you start creating the request?

Kind regards,
Johannes

**Comment by rpauly** [comment]
Thanks! So I tried again..now within 2 mins I get the same error:
> gsva_result <- analyse_sc_clusters(rds_file, verbose = TRUE)
Calculating average cluster expression...
Converting expression data to string... (This may take a moment)
Conversion complete
Submitting request to Reactome API...
Compressing request data...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
> dim(rds_file)
[1]  8000 37414

**Comment by jgriss** [comment]
Hi,

The amount of memory used isn't related to our package but to the 
pipeline you are using to process the scRNA-seq data. We use their 
function (scater or Seurat) to calculate the average cluster expression.

In our own lab we commonly use around 60GB when processing medium sized 
scRNA-seq datasets, going up to 100GB for larger ones.

Especially Seurat often needs quite a lot of memory, mainly since the 
various data types (ie normalized, un-normalized) are all stored in the 
object. But this is also true for Bioconductor based workflows using 
SingleCellExperiment.

Kind regards,
Johannes

**Comment by rpauly** [comment]
Great! Used 247g ...and it works fine! Got the results!
