### ISSUE TITLE
An error when using analyse_sc_clusters

### ISSUE THREAD

**Issue by Byronxy** [reactome/ReactomeGSA#16]
Hi, I tried to use ReactomeGSA to analyze my scRNA-seq data.
However, I met an error like this:
![image](https://user-images.githubusercontent.com/28949856/103478978-3a02d800-4e05-11eb-942b-68a5463c8748.png)

Could you please help out to solve this?
Thanks a lot!

**Comment by jgriss** [comment]
Hi @Byronxy,

Thanks a lot for your interest in ReactomeGSA!

It looks like there was an issue while retrieving the data. I guess you already tried this several times?

If yes, could you try again and send me the timestamp? Then I can compare it with our sever logs.

Additionally, could you also monitor your memory usage? Some issues were caused by insufficient memory while analysing large datasets.

Thanks a lot!

Johannes

**Comment by Byronxy** [comment]
Hi @jgriss ,
Thanks a lot for your help!
Today I try again while don't get this errror. It looks like the issue is caused by the internet?
![image](https://user-images.githubusercontent.com/28949856/103493803-69016400-4e6e-11eb-89e8-a985275cfa23.png)
ReactomeGSA is very helpful. By the way, is there any offline version of this tool? I think it would be helpful when there are internet issues

Thanks a lot!
Byron

**Comment by jgriss** [comment]
Hi @Byronxy ,

Happy to hear that it worked!

Unfortunately, the complete pathway analysis logic is run on our sever. Otherwise, we would not be able to provide the interactive web-based visualizations and continuously update the database. Therefore, we will not be able to provide an offline version of our tool.

But should you be interested, it's fairly straight forward to deploy the web-based application on a local kubernetes cluster.

Kind regards,
Johannes
