### ISSUE TITLE
Error: Only one identification found: 'RNA_snn_res.0.6

### ISSUE THREAD

**Issue by Ankita-1211** [reactome/ReactomeGSA#34]
Hi

I am trying to run reactomeGSA for scRNA seurat result but I am getting this error.

**Error: Only one identification found: 'RNA_snn_res.0.6'. Please ensure that cell / cluster ids are stored as the primary identification (Ident) of your Seurat object. Clustering has to be performed prior to this pathway analysis**.

I know its something related to seurat pipeline, but I have less understanding of this error.

I got another error as well when I just not used this param for my seurat run Idents(seuset) <- "RNA_snn_res.0.6"

**In ReactomeGSA::perform_reactome_analysis(request, verbose = verbose) :
  Reactome Analysis failed: Failed to map any submitted identifiers**

**Comment by jgriss** [comment]
Hi @Ankita-1211,

Thanks a lot for your interest in ReactomeGSA!

You need to store your cluster assignments / cell type assignments as the primary `Ident` in your Seurat object. Otherwise, you don't get any helpful results.

We had a more detailed discussion about this here: #30 

About the identifiers: Which identifier system did you use in your alignment? You can quickly get an example of your identifiers by running:

```R
head(rownames(your_seurat_object))
```

Kind regards,
Johannes
