### ISSUE TITLE
use the latest Reactome release

### ISSUE THREAD

**Issue by jlduan** [reactome/ReactomeGSA#65]
Hi,

Thanks for this wonderful package. I noticed that the default reactome release used is 80. I am wondering if there is a way to select the most recent release 81. Thanks.

**Comment by jgriss** [comment]
Hi @jlduan,

Thanks a lot for reporting this!

You can't select the Reactome version used since this is coupled to our API (we are only able to use one version at a time).

Normally, the update happens automatically, but we had a glitch in our system. This is now fixed and you should receive results from v81 again.

Kind regards,
Johannes
